language: node_js
node_js:
  - lts/*
os:
  - linux
install:
  - npm install
script:
  - npm run docs:build
deploy:
  provider: pages
  cleanup: false
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
